charset_s = "changeda -s charset=UTF-16"
charset_d = "changeda -d charset=UTF-16"
varchar = "changeda -d varchar=no"
varchar_log = "changeda_varchar.txt"
char_s_log = "changeda_charset_s.txt"
char_d_log = "changeda_charset_d.txt"
working_directory = "d:\lmsops\working"